### ISSUE TITLE
the ipa for release 1.1.0 is corrupt

### ISSUE THREAD

**Issue by ptgms** [rasmuslos/AmpFin#11] opened 2024-01-06 01:04 UTC
crashes on launch :(

**Comment by ptgms** [comment] 2024-01-06 01:10
built the IPA myself - still crashes. probably something to do with changes made since 1.0.10.

**Comment by PauFCB** [comment] 2024-01-06 08:02
Same here

**Comment by rasmuslos** [comment] 2024-01-06 15:38
I have made some breaking database migrations, you have to uninstall the app to remove all data, then reinstalling it should work

**Comment by ptgms** [comment] 2024-01-06 17:14
> I have made some breaking database migrations, you have to uninstall the app to remove all data, then reinstalling it should work

I have done that. Still same issue.

**Comment by rasmuslos** [comment] 2024-01-06 21:39
Can you try this build: https://github.com/rasmuslos/AmpFin/releases/tag/v1.1.1 if it does not work please run the app using Xcode and provide the crash logs

**Comment by ptgms** [comment] 2024-01-07 03:03
Build still broken. It did compile and run when I used on emulator- didn't try my actual phone yet. Ill report back when I find time tomorrow

**Comment by rasmuslos** [comment] 2024-01-07 20:34
The app crashed for me when installing the internal TestFlight build after manually installing it via Xcode. I think it is related to the Siri extensions being held in memory and preventing the app from starting properly. Restarting my device did fix it, can you try this, too?

**Comment by ptgms** [comment] 2024-01-07 22:11
Restart didn't work

**Comment by rasmuslos** [comment] 2024-01-08 10:09
I have moved some SwiftData stuff to the appropriate thread, can you try this release: https://github.com/rasmuslos/AmpFin/releases/tag/v1.2.0

**Comment by rasmuslos** [comment] 2024-01-08 11:37
Please try this [version](https://github.com/rasmuslos/AmpFin/releases/tag/v1.2.1), I fixed some bugs where SwiftData operations happened on the wrong thread. Apparently this is not a problem when debugging the executable

**Comment by rasmuslos** [comment] 2024-01-08 17:32
How does the app crash? Is the app (login / library / etc.) visible before it crashes or does the app not even launch? And what tool are you using for side loading (AltStore / Sideloady / Sidestore / Xcode / ...)?

**Comment by ptgms** [comment] 2024-01-08 18:10
I sideloaded using appdb. The app has no view visible - it opens - the view is blurred/black, it's gone. Nothing seems to load.

**Comment by rasmuslos** [comment] 2024-01-08 18:34
Then this bug is most likely caused by appdb. There is [some code](https://github.com/rasmuslos/AmpFin/blob/main/AmpFinKit/Sources/AFBaseKit/HTTP/JellyfinClient.swift#L93) to make app groups work for AltStore and its derivates (like Sidestore), but not for any other side loading alternatives. Most apps don't require app groups because they only store `UserDefaults` data in them, if the app group does not exists this seems to fail silently and just use the default store. The problem is, that this app also stores its SwiftData database in the app group to allow stuff like Siri Intents to work. I tried to find out how appdb creates their app groups, but I could only find a [dead link](https://forum.appdb.to/index.php?/topic/8050-app-groups/) and as the app is closed source there isn't really anything I can do here... Moving the database out of the app group would block a lot of upcoming functionality (Widgets, Siri Intents, etc.), so it isn't really an option.
I would suggest using AltStore / Sidestore / etc. to side load or to wait for the AppStore release.

**Comment by ptgms** [comment] 2024-01-10 18:32
Still crashing

**Comment by PauFCB** [comment] 2024-01-11 14:29
In my case I tried with AltStore and the app let me put my credentials and then closes and I can't open again. Tried restarting

**Comment by PauFCB** [comment] 2024-01-12 15:57
> Did you uninstall version 1.1.0 before installing the newest one? I don't think I have made any changes (not including ones related to the database) that could cause a crash

Yes, I uninstalled first. Hope that soon we can test the app on Testflight 🙏🏻

**Comment by rasmuslos** [comment] 2024-01-13 09:22
This should be fixed here: https://github.com/rasmuslos/AmpFin/releases/tag/v1.2.2
The app group is now disabled, so please strip app extensions, they will not work as intended

**Comment by PauFCB** [comment] 2024-01-13 12:14
still crashing with AltStore, this time don't even opens :(

**Comment by rasmuslos** [comment] 2024-01-13 13:13
I am running out of ideas, the only thing that I can think of that could be the cause is the Siri entitlement, I will provide a build without it later.

And just to clarify, the new build should work with all side loading tools, not just AltStore

**Comment by PauFCB** [comment] 2024-01-13 13:18
Thanks for your work. Yes, tried with AltStore, SideStore and with Scarlet. And also with Apple Configurator 2 that can't even install it. The other ones installs the app but can't open.

**Comment by rasmuslos** [comment] 2024-01-13 14:28
Please try this version: [AmpFin.ipa.zip](https://github.com/rasmuslos/AmpFin/files/13928308/AmpFin.ipa.zip)

**Comment by PauFCB** [comment] 2024-01-13 14:47
https://github.com/rasmuslos/AmpFin/assets/55207285/2c5c9620-9161-4ad2-9393-ef1ec5a7e773

No luck :( with AltStore as you can see and with Scarlet.

**Comment by rasmuslos** [comment] 2024-01-13 14:52
This looks a lot like iOS terminating the app because *something* is wrong with the code signing. The problem is that I cannot say for sure or find out what the error is. I removed all app extensions for this, so can you please try this one: [AmpFin.ipa.zip](https://github.com/rasmuslos/AmpFin/files/13928371/AmpFin.ipa.zip) Make sure tu uninstall the app beforehand, just to be sure

**Comment by PauFCB** [comment] 2024-01-13 14:58
Still not working, but look with the version v1.1.0. The app let me put the credentials but if I close (swiping up) and then try open again I can't. The beyond versions opens perfect.

https://github.com/rasmuslos/AmpFin/assets/55207285/d920d802-60d7-4703-8f0b-3c6344e8eb60

**Comment by rasmuslos** [comment] 2024-01-13 15:06
I am pretty sure that the behavior in v1.1.0 is caused by SwiftData because it it only initialized once you log in. I have one last idea, removing the intent may work... It is about the only change from v1.1.0 to v1.1.1 that could have an impact. If this does not do the trick I have no idea what could cause this.
[AmpFin.ipa.zip](https://github.com/rasmuslos/AmpFin/files/13928529/AmpFin.ipa.zip)

**Comment by PauFCB** [comment] 2024-01-13 15:14
No.. sorry. Let me know if you need to try more things. Thanks

**Comment by rasmuslos** [comment] 2024-01-14 10:47
I will, I have ran out of ideas, so you will have to wait, sorry

And just to clarify: version 1.1.0 works fine and the pre-release 1.1.1 does not anymore?

**Comment by PauFCB** [comment] 2024-01-14 11:14
> I will, but I have ran out of ideas, so you will have to wait, sorry
> 
> And just to clarify: version 1.1.0 works fine and the pre-release 1.1.1 does not anymore?

Sorry if i say the numbers wrong, but the last version without issues opening that I can install with all the sideload apps (AltStore,Scarlet, etc) is the last one called Music.ipa. The versions called AmpFin.ipa and beyond have problems like crashing or, in the best case, put the credentials.

**Comment by rasmuslos** [comment] 2024-01-14 11:16
So the last working version is v1.0.10 and it stopped working in v1.1.0?

**Comment by PauFCB** [comment] 2024-01-14 11:21
> So the last working version is v1.0.10 and it stopped working in v1.1.0?

Yes. 1.0.10 works well and 1.1.0 can be installed with AltStore but only for credentials (note that once open well and navigate into the Playlists section but only show the Playlis name, not any song even refreshing, but this only happens one time, the rest closes when I try to open).
Beyond versions don't let me open.
(Excuse me for my English).

**Comment by rasmuslos** [comment] 2024-01-14 12:11
So v1.1.0 does not crash when opening, only when navigating to something other then playlists? What version of the server are you using?

**Comment by PauFCB** [comment] 2024-01-14 13:54
> So v1.1.0 does not crash when opening, only when navigating to something other then playlists? What version of the server are you using?

1.1.0 can only be oponed if I install it with AltStore while previous versions it doesn't matter what side load app I use for. For example, If I install 1.1.0 using Scarlet, the app don't open. But if install it with AltStore, I can open the app and even use it normally, but in the playlist section, it only appears the name and number of the track, but can't see the name of the songs and the cover of each playlists and if I click the play/shuffle nothing happens. Is for this issue that I prefer to use the 1.0.10 version whit Scarlet (and for no need a PC). 
Beyond versions I tried everything but crashes and can't open.

**Comment by rasmuslos** [comment] 2024-01-22 10:43
Well then it seems like there were multiple issues. The crash in v1.1.0 with scarlet is expected, the playlist thing not. I guess the Siri entitlement is causing the crash in v1.1.1 and above, but if the other releases did not work either, I have no clue what could cause the crash. I have also no way of knowing if it works for other people so I really have no idea on what to do, sorry

**Comment by PauFCB** [comment] 2024-01-22 15:00
Hope more people can test and find the errors.

**Comment by rasmuslos** [comment] 2024-01-23 14:48
So it seems like the crash also occurred in ShelfPlayer (https://github.com/rasmuslos/ShelfPlayer/issues/20), and luckily we were able to find its cause. I will provide a fix soon

**Comment by rasmuslos** [comment] 2024-01-23 15:45
Please try this version: https://github.com/rasmuslos/AmpFin/releases/tag/v1.2.3

**Comment by PauFCB** [comment] 2024-01-23 17:41
Working! The playlist section still don't work properly when you open one but the app don't crash and it's usable. Thanks
![IMG_2654](https://github.com/rasmuslos/AmpFin/assets/55207285/5186001a-1d0b-4f04-9360-5f961a1257cf)

**Comment by rasmuslos** [comment] 2024-01-23 19:05
The playlist thing is a separate issue, please open another one. Can you also include some information about the playlist there, like if there are any other media types (other than tracks) in it

**Closed by rasmuslos** 2024-01-23 19:05 UTC
