### ISSUE TITLE
Playlist bug

### ISSUE THREAD

**Issue by PauFCB** [rasmuslos/AmpFin#16] opened 2024-01-27 15:02 UTC
The playlist show the name, total tracks and duration but not the cover and can't be played or shuffled
![IMG_2662](https://github.com/rasmuslos/AmpFin/assets/55207285/35e02f8b-0840-42cb-ab19-963191a39624)

**Comment by rasmuslos** [comment] 2024-01-29 16:40
The cover is actually working as intended, but judging by the size of the playlist I think one of the tracks is not converted correctly. Does the "Tracks" library section work for you?

**Comment by rasmuslos** [comment] 2024-01-29 20:53
In the online & offline tab?

**Comment by PauFCB** [comment] 2024-02-03 12:24
> In the online & offline tab?

I don't know if when offline too because I can't download anything, the spinner that indicates the download process never stops

**Comment by rasmuslos** [comment] 2024-02-04 11:13
Are there any other item types (so for example movies, episodes, etc.) in the playlist? I think the APIClient cannot parse the response it is getting from the server. And if you are able to view all of you tracks in the library tab this is the most likely cause

**Comment by PauFCB** [comment] 2024-02-04 14:00
No, only flac mp3 and m4a files that working on the web version and other clients (finamp, fintunes)

**Comment by PauFCB** [comment] 2024-02-04 14:17
Some more screenshots if that help. First one is when try to add a song to a playlist and the second one the current message on the playlist section.
![IMG_2709](https://github.com/rasmuslos/AmpFin/assets/55207285/c1340441-b472-4f80-bce3-8e0c3ab342be)
![IMG_2710](https://github.com/rasmuslos/AmpFin/assets/55207285/a92a9524-8bcd-4eb3-a2ce-ea026b46d10d)

**Comment by rasmuslos** [comment] 2024-02-07 09:50
This is really wired, it seems like there is something wrong with your playlists, not the tracks themselves. Have you tried the latest build, I have made some updates to the playlist parsing logic.

Also, can you run the app using Xcode to provide a more detailed error message?

**Comment by PauFCB** [comment] 2024-02-07 18:16
I try with different playlist (all flac 16/44), working with the web version and other clients but still not working with the latest release, and a new bug appears, playlist duration. 
![IMG_2715](https://github.com/rasmuslos/AmpFin/assets/55207285/0d9cc6d2-3f77-412b-a688-9559c004c61c)
Apart from that, the app working fast and good (only the artist bios: sometimes it shows and sometimes don't).

**Comment by rasmuslos** [comment] 2024-02-09 09:01
Can you share a screenshot of the playlist? And thanks for the kind words, I guess the artists don't have a bio set in Jellyfin, otherwise please open a separate issue.

**Comment by PauFCB** [comment] 2024-02-09 18:19
It's attached above, thanks

**Comment by rasmuslos** [comment] 2024-02-20 11:42
Can you try this build:
[AmpFin.ipa.zip](https://github.com/rasmuslos/AmpFin/files/14343754/AmpFin.ipa.zip)

**Comment by PauFCB** [comment] 2024-02-23 11:20
Now I can play and shuffle the playlist normally but the total duration isn't correct yet.

**Comment by rasmuslos** [comment] 2024-02-23 11:25
Do all tracks show up? The duration might not be correct because the new versions removes tracks that cannot be parsed. So you might have some tracks in your playlist that do not belong to an album, which are now removed and not counted to the total duration.

**Comment by rasmuslos** [comment] 2024-02-23 17:37
> > Do all tracks show up? The duration might not be correct because the new versions removes tracks that cannot be parsed. So you might have some tracks in your playlist that do not belong to an album, which are now removed and not counted to the total duration.
> 
> Maybe the thing that I have some singles that not belongs to any album be the reason

This could be the reason, but it is more likely that some albums are not parsed correctly.

But do the other tracks show up?

**Comment by PauFCB** [comment] 2024-02-23 17:46
Yes it show all the tracks and can play and shuffle only the total playlist duration is wrong, but it's correct for each song individually

**Comment by PauFCB** [comment] 2024-02-24 14:07
Its too long, like millions of hours for a 100 songs playlist,

**Comment by rasmuslos** [comment] 2024-02-25 10:37
Did you download the playlist? Because the duration is parsed directly from the Jellyfin server https://github.com/rasmuslos/AmpFin/blob/main/AmpFinKit/Sources/AFBase/Extensions/Item/Playlist+Convert.swift

**Comment by PauFCB** [comment] 2024-02-25 12:40
No, only stream, I don't download anything yet

**Comment by rasmuslos** [comment] 2024-02-25 12:56
Is the time reported correctly in the web interface?

**Comment by PauFCB** [comment] 2024-02-25 14:08
yes, 6h 49min vs 11.554.680h total duration. It's not an importan bug, because when a song start playing the time it's correct for each song, but the total duration stay the same.

**Comment by rasmuslos** [comment] 2024-02-28 15:28
The main issue has been resolved, so I will close this. I will keep an eye out for this bug, but for now I don't know where it could come from...

**Closed by rasmuslos** 2024-02-28 15:28 UTC

**Comment by gfoldv** [comment] 2024-02-29 18:52
@rasmuslos in the above mentioned [code](https://github.com/rasmuslos/AmpFin/blob/main/AmpFinKit/Sources/AFBase/Extensions/Item/Playlist+Convert.swift) the division by 10_000_000 is not applied since the **item.RunTimeTicks** has value.
You need to apply the ?? operator first, like
`duration: Double((item.RunTimeTicks ?? 0) / 10_000_000)`

**Comment by rasmuslos** [comment] 2024-02-29 19:05
> @rasmuslos in the above mentioned [code](https://github.com/rasmuslos/AmpFin/blob/main/AmpFinKit/Sources/AFBase/Extensions/Item/Playlist+Convert.swift) the division by 10_000_000 is not applied since the **item.RunTimeTicks** has value. You need to apply the ?? operator first, like `duration: Double((item.RunTimeTicks ?? 0) / 10_000_000)`

I am really stupid, thanks a lot! Normally I notice this mistake but apparently not this time...
